"""
Django settings for denshoapi project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import configparser
from pathlib import Path
from urllib.parse import urljoin

BASE_DIR = Path(__file__).parent.parent

with Path.joinpath(BASE_DIR, '..', 'VERSION').open('r') as f:
    VERSION = f.read().strip()

CONFIG_FILES = [
    '/etc/ddr/denshoapi.cfg',
    '/etc/ddr/denshoapi-local.cfg'
]

config = configparser.ConfigParser()
configs_read = config.read(CONFIG_FILES)
if not configs_read:
    raise Exception('No config file!')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.get('app', 'secret_key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.getboolean('app', 'debug')

BASE_URL = config.get('app', 'base_url')

ALLOWED_HOSTS = [
    host.strip()
    for host in config.get('app', 'allowed_hosts').split(',')
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    #
    'corsheaders',
    'rest_framework',
    'drf_yasg',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsPostCsrfMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'denshoapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'denshoapi.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_ROOT = config.get('app', 'static_root')
STATIC_URL = '/static/'

MEDIA_ROOT = config.get('app', 'media_root')
MEDIA_URL = '/media/'


# REST interface

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

SWAGGER_BASE_URL = urljoin(BASE_URL, '/api/swagger/')
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'basic': {
            'type': 'basic'
        }
    },
    'DEFAULT_INFO': 'denshoapi.urls.api_info',
}

# django-cors-headers (see https://github.com/ottoyiu/django-cors-headers/)
CORS_ORIGIN_ALLOW_ALL = config.getboolean('app', 'cors_origin_allow_all')
CORS_ORIGIN_WHITELIST = [
    domain.strip()
    for domain in config.get('app', 'cors_origin_whitelist').split(',')
]
## Only send CORS headers for API.
#CORS_URLS_REGEX = r'^/api/.*$'

# TESTING CORS HEADERS
# http GET http://192.168.56.188:8010/api/accounts/profile/ "Authorization: Token b39fe365c25481da697e41f5ec56e9d2241b5435"

# http GET http://192.168.56.188:8010/api/accounts/profile/ "Authorization: Token b39fe365c25481da697e41f5ec56e9d2241b5435" "Origin: http://127.0.0.1"

# http GET http://192.168.56.188:8010/api/accounts/profile/ "Authorization: Token b39fe365c25481da697e41f5ec56e9d2241b5435" "Origin: http://192.168.56.1"
